SHARE_DIR = /media/sf_ArchData

.PHONY: clean_a clean_b clean_c send_a send_b send_c

clean_a:
	rm -rf data_a/*

clean_b:
	rm -rf data_b/*

clean_c:
	rm -rf data_c/*

clean_d:
	rm -rf data_d/*

clean_e:
	rm -rf data_e/*

send_a:
	rm -rf $(SHARE_DIR)/data_a
	cp -rf data_a $(SHARE_DIR)/data_a

send_b:
	rm -rf $(SHARE_DIR)/data_b
	cp -rf data_b $(SHARE_DIR)/data_b

send_c:
	rm -rf $(SHARE_DIR)/data_c
	cp -rf data_c $(SHARE_DIR)/data_c

send_d:
	rm -rf $(SHARE_DIR)/data_d
	cp -rf data_d $(SHARE_DIR)/data_d

send_e:
	rm -rf $(SHARE_DIR)/data_e
	cp -rf data_e $(SHARE_DIR)/data_e
